#!/bin/bash
source /app/functions.sh;

overwrite_default_file /data/KFGame/Config/LinuxServer-KFGame.ini /app/killing-floor-2/KFGame/Config/LinuxServer-KFGame.ini.example;
link_data /data /app/killing-floor-2;

source kf2_functions.sh

require_config
load_config
launch

